### ISSUE TITLE
Probe widget

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#1]
- HTML/SVG/d3.js view for a probe
- Show the layout (channel positions) with discs
- Equal normalization for x and y axes
- Display it with `_repr_html_()` of the MEA class

**Comment by rossant** [comment]
suggestion by @nsteinme 

> In my imagination, this shows the spatial layout with little squares at each site location and lines drawn between them according to the connectivity - really simple. It could have a different color square for channels that exist on the probe but aren't going to be included, and if it were ever-so-slightly more than "read-only", allowing you to click a site to toggle including/excluding it, that would be a very nice feature.

**Comment by nippoo** [comment]
This is 100% what I was imagining. And an option to toggle channel numbers in the squares...
