### ISSUE TITLE
Programmatic high-contrast colour generation

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#105]
- Generate a list of colours automatically based on highest-contrast between neighbouring colours (see http://devmag.org.za/2012/07/29/how-to-choose-colours-procedurally-algorithms/).
- Return white/black highest contrast text (several algorithms to do this!)
- Needs to be colourblind-friendly
- Can specify "must be bright" or "must be dark" or "must be neutral" - high-contrast with black or white, or both

**Comment by rossant** [comment]
see https://github.com/kwikteam/phy/blob/master/phy/utils/_color.py#L26

**Comment by rossant** [comment]
Maybe add:

* Generate manually a colormap of 10-20 (even 30?) colors that are:
    * light enough to be well visible on a black background
    * color n should be quite distinct from color n+1

We'll use this colormap when assigning colors to new clusters.

**Comment by rossant** [comment]
@nippoo It might be sufficient to generate a single colormap that has all required properties. The first selected cluster will get the first color, the second one the second color, etc.

**Comment by rossant** [comment]
There now is a good enough colormap
