### ISSUE TITLE
Test minimal no-anaconda environment on Travis

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#115]
With `apt-get` exclusively.

**Comment by rossant** [comment]
See [this](https://github.com/vispy/vispy/blob/master/.travis.yml) for an example of a `.travis.yml` with multiple configs.

**Comment by nippoo** [comment]
What should our minimal supported config be?

**Comment by rossant** [comment]
I would suggest to try the latest Ubuntu LTS (so 14.04) with the latest Ubuntu apt-get packages for NumPy, h5py, etc. We'll see if we get incompatibilities then.

**Comment by nippoo** [comment]
Okay! I suspect we'll have to install IPython manually with pip though?... since the stable version is 1.2 on Ubuntu's repo

**Comment by nippoo** [comment]
Do we want it to be Python2 or Python3? Or we could do both.

**Comment by rossant** [comment]
Hmm, yes probably. Hopefully that should be fine because IPython is pure Python. But the notebook comes with many dependencies. (PS: IPython 3.0 will be released in a couple of weeks)

**Comment by rossant** [comment]
> Do we want it to be Python2 or Python3? Or we could do both.

I would say Python 2 only for now. We can assume that those who want bleeding edge Python 3 will be okay with using anaconda...
