### ISSUE TITLE
Clustering GUI

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#128]
The goal of this issue is to implement (in phyui?) a clustering GUI based on PyQt and IPython notebook. The GUI wraps a `Session` instance which implements the logic. The logic (Session) and the GUI code are completely separated. You don't have to use the GUI to work with your data: you can just use the Session API for this.

The [`Session`](https://github.com/kwikteam/phy/blob/master/phy/cluster/manual/session.py) class implements the clustering logic:

* `session.open(file)` 
* `session.select(clusters)`
* `session.merge(clusters)`
* `session.undo()`
* etc.

There is no graphical/visualization part involved in `Session`.

The goal of the `GUI` class is to wrap a Session and implements an actual GUI, in HTML, Qt, or anything else.

Here is the base class:

```
class BaseGUI(object):
    def __init__(self, session):
        self._session = session

    @property
    def model(self):
        return self._session.model

    @property
    def session(self):
        return self._session

    def show(self):
        raise NotImplementedError()
```

Then we have a `ClusteringGUI(BaseGUI)` that implements the clustering GUI with PyQt for the main window and the VisPy canvases, and HTML/IPython/JS/D3 for the cluster view. Later on we'll have a `TemplateMatchingGUI(BaseGUI)` as well.

The GUI can be used like this:

```
gui = ClusteringGUI(session)
gui.show()  # display the QMainWindow with the default VisPy views and the ClusterView as well in the notebook (an error is raised if we're not in the notebook)

gui.show_cluster_view()  # just display the cluster view in the current notebook cell
gui.add_waveform_view()  # add a waveform view in the QMainWindow (there can be several views of the same type in the GUI)
gui.add_feature_view()  # idem
gui.add_correlograms_view()  # idem

gui.feature_views()  # return a list of Feature view instances

gui.session.open(file)  # this just opens a file using the wrapped Session instance
gui.session.merge(clusters)  # this just merges some clusters

gui.prompt_file()  # opens a FileDialog, the user selects a file, and the file is opened
gui.reset_views()  # reset the views to their default state
gui.save_views(file=None)  # save the current positions of the different views in a given file, or in a default location (e.g. ~/.phy/clustering_gui/qt_settings)

```

See some old code here (most of it won't be used, except some of the styles maybe):

* https://github.com/klusta-team/klustaviewa/blob/master/klustaviewa/gui/mainwindow.py
* https://github.com/klusta-team/klustaviewa/blob/master/klustaviewa/gui/dock.py
* https://github.com/klusta-team/klustaviewa/blob/master/klustaviewa/gui/styles.css

**Comment by cgestes** [comment]
here we go
