### ISSUE TITLE
Internal directory structure

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#143]
The library keeps its data in `~/.phy` by default. The user shouldn't have to deal with this directory in normal circumstances, but they could do it for advanced uses or troubleshooting.

### User-defined settings

Defined in one or several Python files editable by the user. *Not edited by the library*.

* Global
* Per data

Examples:

* marker size in the feature view (global)
* scale factor in the waveform view (per data)
* spike detection/clustering default parameters

### GUI settings

Defined in an automatically-generated text. *Not edited by the user*.

* Global
* Per data

Examples:

* placement of the widgets in the Qt GUI (this is a format internal to Qt)
* size and possibly positions of the VisPy views
* recently-opened files

### Clustering data

Per data.

* cluster store
* clustering history (*not implemented yet*)

## Directory structure

In `~/.phy/`:

```
global/
    clustering_gui  # GUI options
    settings.py
my-dataset-1/  # this is a filename
    cluster_store/
        0001.h5  # one file per cluster
        ...
    clustering_gui  # GUI options
    settings.py
```

**Comment by nippoo** [comment]
I'd go with something like the following:

##Conventions
```
EXPBASE = experiment123
EXPFOLDER = /path/to/experiment/
```

* Global data in `~/.phy/`
* Per-experiment data in `EXPFOLDER/EXPNAME_phy` (so you can have multiple experiments in one folder - also EXPNAME before _phy so you can do things like `mv EXPNAME* /new/path/ in one command)

Examples:

* marker size in the feature view (global)
* scale factor in the waveform view (per data)
* spike detection/clustering default parameters

### GUI settings

Defined in an automatically-generated text. *Not edited by the user*.

* Global
* Per data

Examples:

* placement of the widgets in the Qt GUI (this is a format internal to Qt)
* size and possibly positions of the VisPy views
* recently-opened files

### Clustering data

Per data.

* cluster store
* clustering history (*not implemented yet*)

## Directory structure

In `~/.phy/`:
```
gui_settings.py # GUI options
default_params.py # KlustaKwik / spike detection default options etc
phy_state # Qt last view state, recently modified files, size of views etc - AUTOGEN
```

In `EXPFOLDER/EXPBASE_phy`:
```
params.py # KlustaKwik / spike detection options etc
exp_state # Qt view internal savestate (waveform view scaling, channel height etc) - AUTOGEN
[optional, user-created] gui_settings.py # override default GUI settings (reduce spike sample size for huge datasets etc etc)
cluster_store/
      001.phycluster
      002.phycluster
```
