### ISSUE TITLE
Choose between clusters or cluster_ids

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#194]
Currently, both are used interchangeably. We should stick to one.

@nippoo for example, in the `Clustering` class, the list of current cluster identifiers is `cluster_ids`. Should we choose `clusters` or `cluster_ids` in all such instances?

**Comment by nippoo** [comment]
cluster_ids :)

**Comment by nippoo** [comment]
cluster_ids is much less ambiguous - it's a list of the IDs of clusters. "clusters" could be anything - objects containing cluster information? ...

**Comment by rossant** [comment]
Agreed, that was my initial motivation, but I've become a bit lazy with time... :)
