### ISSUE TITLE
More robust cluster store generation

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#196]
When loading a dataset, check if the cluster store exists. If not, create it. Otherwise, check the file size of every file. If all's good, do not regenerate it. Otherwise, if there's an inconsistency, display a warning, and recreate the corrupted or missing files.

The user should be warned that changing the spike clusters manually necessitates to force the regeneration of the cluster store.

**Comment by cgestes** [comment]
do not use filesize? it doesnt mean data are consistent.

Multiples solutions:
- store md5 / sha1 of files. then recreate data if something is wrong. this does not fix concurrency.
- create a file that state you are writting to the datastore with the pid of the process writting.
  - if the pid exists do not write to the data store. 
  - if the pid do not exists, remove the file and fix the repo.
This ensure that two process cannot write to the cache at the same time, but does not check coherency.
- do both :)
