### ISSUE TITLE
Option to only zoom in the subplot hovered by the mouse pointer

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#198]
* [x] Independent panning/zooming in the subplots
* [x] alt+wheel = global zooming
* [x] anisotropic zooming with right click

Can use a uniform with the index of the currently-hovered subplot, and if statement for pan/zoom in GLSL.

**Comment by rossant** [comment]
@shabnamkadir @nsteinme @nippoo at some point I'd appreciate feedback on the pan/zoom UX in the 3 different views. I've improved it in an upcoming PR, but there are still some minor issues.

**Comment by rossant** [comment]
@nsteinme thanks for the feedback. Do you think it would be interesting to have an option to switch between the two behaviors (current one, and independent zooming in each plot), or is it okay to just have the independent zooming option?

**Comment by nsteinme** [comment]
I think switching between both is useful - it's good to do all at once if, for instance, they're all wildly mis-scaled at the moment. But you can definitely imagine wanting to scale them independently. 

Btw there was one part of the other issue I posted that isn't covered here (sorry for double-posting again) - should be able to scale y-axis separately from x. I didn't figure out how to do this yet (it doesn't work like in KV, at least).

**Comment by rossant** [comment]
> Btw there was one part of the other issue I posted that isn't covered here (sorry for double-posting again) - should be able to scale y-axis separately from x. I didn't figure out how to do this yet (it doesn't work like in KV, at least).

Ah sorry I had missed that. Are you referring specifically to the feature view, or the other views too? I figured it wasn't that useful to scale the axes independently, and it seemed to me that most users were confused about it (or didn't even know that feature!). In many cases you want to keep the aspect ratio fixed. Could you precise in which situation it is useful to scale the axes independently?

**Comment by nippoo** [comment]
The default behaviour should definitely be to scale the views
independently. Perhaps holding down a modifier key could trigger rescaling
all the views? In any case, I'm not sure if/why you'd want to pan them all,
it might be limited only to zoom, since they're all projections of
different dimensions. I can definitely seeing it be more of an annoyance if
it's easy to do it accidentally...

**Comment by nsteinme** [comment]
I use it all the time in KV when one dimension is much larger than another, e.g. to go from this (the default original appearance):

![image](https://cloud.githubusercontent.com/assets/7590975/7395915/448937f4-ee95-11e4-8002-0c1e542361b3.png)

to this: 

![image](https://cloud.githubusercontent.com/assets/7590975/7395931/5d88dbba-ee95-11e4-8343-4b806ea049b5.png)

**Comment by nsteinme** [comment]
In KV you just right click and drag around - things scale in a really nice and intuitive way. This behavior should be retained, I think.

**Comment by rossant** [comment]
> In KV you just right click and drag around - things scale in a really nice and intuitive way. This behavior should be retained, I think.

Personally I agree, but you're the first one I know who thinks that way :)

I'm +0.5 on adding that functionality, because then you have several scaling options that are mixed together. I can understand that it gets confusing to most users except the most advanced ones. In the waveform view, you can easily change the scaling of the waveforms with the keyboard. Idem for the probe. Add to that the independent scaling with right click and you get 3 ways to get the same thing... @nippoo wdyt? I'd be curious to have the opinion of more users (Ken, Shabnam, I-Chun, Aman, etc.)

**Comment by rossant** [comment]
> I use it all the time in KV when one dimension is much larger than another, e.g. to go from this (the default original appearance):

I also agree that at least the time dimension deserves independent scaling.

**Comment by rossant** [comment]
> The default behaviour should definitely be to scale the views
> independently. Perhaps holding down a modifier key could trigger rescaling
> all the views?

Yep. What about this:

* default is independent pan/zoom in the boxes
* alt + mouse wheel = same zoom gets applied to all boxes
* you cannot pan globally in all boxes together

**Comment by nsteinme** [comment]
That makes good sense to me.

**Comment by nippoo** [comment]
Yep, something like that is fine. Also very much +1 on the need to zoom
different dimensions independently. Sometimes you'll have a cluster with a
really elongated shape which almost looks like a straight line, and you
want to 'widen' it: normally you basically want to fill the view with
whatever cluster you're looking at, or where you want to split, or another
cluster, or whatever, and unless the cluster is circular (as opposed to
elliptical etc) you want to be able to fill it. I think...

**Comment by rossant** [comment]
phew.. done!! it took me the whole day...
