### ISSUE TITLE
Integrate a set of common probes

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#214]
* Tetrode
* 8-channel
* 32-channel
* ...

**Comment by nippoo** [comment]
Wait for NWB etc to specify a common probe format.

**Comment by rossant** [comment]
* we can keep the current format for now
* override channel mapping in prm
* each probe has a unique name
* probes are referred by their names in the PRM
* a probe with name X is found in the following directories by decreasing order of priority
  * experiment dir
  * `~/.phy/probes/X.prb`
  * `phy/electrode/probes/X.prb` (in phy's directory)
  * an error is raised
