### ISSUE TITLE
waveform view doesn't allow resizing/scaling

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#225]
Unable to change the y-axis scaling or relative spacing of waveforms on different channels in waveform view. In KV these are ctrl+mouseWheel and shift+mouseWheel. 

On windows 7, master branch.

**Comment by rossant** [comment]
Try Ctrl+arrows and Shift+arrows

https://github.com/kwikteam/phy/blob/master/phy/plot/waveforms.py#L159

**Comment by nsteinme** [comment]
Great, that works, sorry - Max and I thought we tried everything ;)
