### ISSUE TITLE
Upload test datasets

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#247]

**Comment by nippoo** [comment]
Done. http://phy.cortexlab.net/data/

**Comment by rossant** [comment]
thx! why put both md5 and filename in .md5 file? the current implementation assumes there's just the md5 in the fie

**Comment by nippoo** [comment]
It's the output of "md5sum file.kwik > file.kwik.md5"

"md5sum" outputs the filename too. and offers a double-check against the
filename being correct! but it's possible to change if you want...
