### ISSUE TITLE
Doc build system

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#255]
phy.cortexlab.net/doc/ hosts the main doc using some parser or something. we update this via a post-commit hook on the DOC repo which just pulls the doc onto the server whenever there's a commit made to the repo.
phy.cortexlab.net/doc/api/ hosts the api autogen doc. this is updated automatically via a post-commit hook on the MAIN repo which pulls the main repo, then runs api-autogen.py whenever there's a commit made to the repo.
so essentially you then have one component, literally just an HTTP request to update what you want:
phy.cortexlab.net/doc/doc_magic_update.py?update=doc
phy.cortexlab.net/doc/doc_magic_update.py?update=api
phy.cortexlab.net/doc/doc_magic_update.py?update=all

**Comment by nippoo** [comment]
let's close this for the moment - readthedocs with the MD parser might do what we want.
