### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#257]
* [x] Check `setup.py`
* [x] Set `phy.__version__`
* [x] Upload dev version on pypi
* [x] Check `make test-quick` on docker
* [x] Bump version final in PR && git commit push && `make release`
* [x] Merge PR
* [x] Test with `make test-docker`
* [x] Tag
* [x] Upload on GH releases
* [x] Announcement on the mailing list

**Comment by nippoo** [comment]
Cool. I'll get feedback at the meeting tomorrow then I'll get on it!
