### ISSUE TITLE
Big Refactoring

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#271]
* [x] Refactor utilities
* [x] Refactor `phy.io`: `phy.io.mock`, `phy.io.kwik.model`, `phy.io.kwik.mock`
* [x] Move cluster store to `phy.io`
* [x] Move `features_masks` and `waveforms` store items to `phy.io.kwik`
* [x] `phy.plot.view_models` with `kwik` and `_base`

cc @nippoo

**Comment by nippoo** [comment]
Where will things like a PSTH or CCG generator go? Other analysis functions which don't necessarily return graphs, but instead return numbers or a mean waveform etc etc? I'm just wondering what's best for things that could live in `phy.plot` but might not strictly be plotting-related...

**Comment by rossant** [comment]
`phy.stats`?
Then we can have generic plotting functions for things like PSTH in `phy.plot`

**Comment by nippoo** [comment]
Yes, that seems good. Decouple the data analysis bits from the plotting as much as possible!
