### ISSUE TITLE
Clearer error when kwik does not exist

### ISSUE THREAD

**Issue by shabnamkadir** [kwikteam/phy#274]
More clear error needed for this.

I like bananas.

dir/phytest/phy/phy/io/kwik_model.pyc in open(self, kwik_path, channel_group, clustering)
    648         # Open the KWIK file.
    649         self._kwik = self._open_h5_if_exists('kwik')
--> 650         if not self._kwik.is_open():
    651             raise ValueError("File {0} failed to open.".format(kwik_path))
    652         self._check_kwik_version()

AttributeError: 'NoneType' object has no attribute 'is_open'

**Comment by shabnamkadir** [comment]
OK, so jsut to let you know. The problem was caused by a typo - I pointed to a file that did not exist.

**Comment by rossant** [comment]
ok I guess that a clearer message should be raised then
