### ISSUE TITLE
Implement a way to select features from the GUI

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#290]

**Comment by rossant** [comment]
1+click in waveform view?
should bind to ctrl and shift too though

**Comment by rossant** [comment]
can this be closed?

**Comment by nippoo** [comment]
@nsteinme ... this is your issue. Apparently you "can't select features". What did you mean?

**Comment by nsteinme** [comment]
Aha! Sorry, I didn't realize this 1+click etc had been implemented. That's great! Closed.
