### ISSUE TITLE
Some waveform pan/zoom controls missing

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#292]
@nsteinme which particular action[s] would you need which aren't currently implemented?

**Comment by nsteinme** [comment]
There's nothing that's impossible to do, but separating individual probe
sites laterally (in the x direction) could be achieved with mouse controls
in KV but is ctrl+left/right arrow in phy. It's definitely faster/nicer to
have everything on the mouse; however, like I said this is really minor...

**Comment by rossant** [comment]
can you remind me what mouse controls would be effective here?

**Comment by rossant** [comment]
(incidentally the reason why there are more keyboard shortcuts and less mouse shortcuts is that i now use a laptop without mouse + i have a broken hand so keyboard is easier for me :p)

**Comment by rossant** [comment]
done
see https://github.com/rossant/phy/blob/bug-fixes/phy/plot/waveforms.py#L300-L313

**Comment by nsteinme** [comment]
Ok, great, sorry I went back again and I can't figure out what exactly I thought was missing. I may have been confused. Apologies...

**Comment by rossant** [comment]
well I just implemented new shortcuts after your suggestions so that was definitely useful! :)
