### ISSUE TITLE
No way to cancel and re-draw lasso without split then undo

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#294]

**Comment by rossant** [comment]
shift+click?

**Comment by nippoo** [comment]
I think double-click anywhere in the view would be much more intuitive...

**Comment by rossant** [comment]
well i mean it should already work with that shortcut
but we can change it
double click is to enlarge a subplot currently (ken's proposition)

**Comment by rossant** [comment]
sorry it is ctrl+right click currently!

**Comment by rossant** [comment]
can this be closed.
