### ISSUE TITLE
autocorrelogram and crosscorrelogram should be computed for much more than 10k points (all, if possible)

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#298]
It's again because if you have one unit with few points relative to the other, you completely lose its ccg. Furthermore, the number of CCG refractory violations is a relevant measure and you're simply not displaying them by selecting only a subset of points. 

Could the CCGs be computed up front and cached? For ACGs can they be computed with much higher number of points included?

**Comment by rossant** [comment]
i'm not sure this is a problem: the subset spikes belong to contiguous chunks
like `spikes[0:1000]`, `spikes[2000:3000]` etc where `spikes`  is the array of *all* spikes in increasing order

**Comment by rossant** [comment]
btw do you know that you can change the parameters? create a `~/.phy/user_settings.py` with new parameters

**Comment by nsteinme** [comment]
How long would it take to compute the CCGs for all spikes? What if there was a hotkey you could press for situations in which you really wanted to see the whole CCG (these situations are relatively rare). Or, sounds like this is a good case for the interactive - what kind of command would I have to enter to make and plot a ccg with all spikes from two clusters?

**Comment by rossant** [comment]
hmm actually where did you get the 10k figure? looking at the [default parameters](https://github.com/kwikteam/phy/blob/master/phy/cluster/manual/default_settings.py#L12-L19) it looks like the CCGs and ACGs are computed from 1M spikes in 10 chunks of 100k consecutive spikes.

you can change that: create a `~/.phy/user_settings.py` and copy paste from the default settings the lines you want to change

you should also be able to add a new view with custom parameters, this should be documented at the last section of the user guide
