### ISSUE TITLE
Basic FeatureView

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#30]
* Just a scatter plot of selected spikes
* Subset of all spikes from a list of given clusters
* Point colors as a function of the cluster
* Refactor WaveformVisual in a BaseVisual with baking mechanism

**Comment by nippoo** [comment]
Probably need to display only a subset of points, but in an intelligent way so information on outliers is always preserved i.e. heatmap (using a locality-sensitive structure for storing them?)
