### ISSUE TITLE
Optimize waveform creation in store

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#301]
load spike after spike instead of cluster after cluster (to preserve IO contiguity)

**Comment by nippoo** [comment]
YAGNI (HDD-only)

**Comment by rossant** [comment]
Fetch waveform subsets regularly from the raw data during the creation of the cluster store before storing them cluster-by-cluster. cc @nsteinme

**Comment by rossant** [comment]
in fact @nsteinme doing `waveforms_excerpt_size = None` in your `user_settings.py` should suffice no?

**Comment by nsteinme** [comment]
Sorry to be slow but I didn't test this yet...

**Comment by rossant** [comment]
@nippoo will do a prerelease and you can test it then
