### ISSUE TITLE
Improve double-click zooming in grid view

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#306]
The current implementation is a bit hackish and buggy. A few options

* Implement it more generally in `_panzoom`
* Implement it partially on the GPU
* Alternative: use a separate window with only 1 subplot, and bind it to double click (simpler implementation)

The tricky part in the implementation is to keep the state of all internal variables (including local pan zoom, constraints, etc) and reset them when the enlarge option is disabled.

@nsteinme what do you think of the alternative? basically you'd have two feature views, one 4x4 and one 1x1. By double clicking on a subplot it would zoom in the *other* view. This would make my life easier :) however it would take more place on your screen.

**Comment by nsteinme** [comment]
I like the separate-window idea - I think I'd even prefer it. Go for it!
