### ISSUE TITLE
Show statistics of multiple clusters in stats view

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#324]
Using an HTML table (row=stat, column=cluster)

**Comment by rossant** [comment]
@nsteinme @nippoo do you feel this is urgently needed or not?
currently, the stats of the first selected cluster only are shown

![image](https://cloud.githubusercontent.com/assets/1942359/8068320/76c23a9e-0ef3-11e5-88da-7ed63f63cfcf.png)

also, this might change a bit when the cluster view is done (it won't be ready before some time)

**Comment by nsteinme** [comment]
Ideally you'd want to see both, but only showing the first one should be
mostly fine. I will do some clustering with this and let you know if I'm
feeling like I really need to see both at once. Thanks!

**Comment by rossant** [comment]
ok dw it's done in the PR!
