### ISSUE TITLE
Set up readthedocs

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#325]
on `phy.cortexlab.net`

**Comment by rossant** [comment]
@nippoo this is done no?

**Comment by nippoo** [comment]
Hey, yeah, this is basically done. Still have a couple of things to debug though. I'll do and close it tomorrow

**Comment by rossant** [comment]
do you need help on this one? i may have some time

**Comment by nippoo** [comment]
Done!

**Comment by rossant** [comment]
excellent! so if I update phy-doc/master, it will "just work"?

**Comment by nippoo** [comment]
yes! :)
