### ISSUE TITLE
Keybord shortcuts are hard to find

### ISSUE THREAD

**Issue by lepmik** [kwikteam/phy#337]
when pressing ctrl+h you only get Keyboard shortcuts for ClusterManualGUI, however to get the other shortcuts you have to mouse click on a specific window and press h

Opening test_hybrid_120sec.kwik
Running ubuntu 14.04

**Comment by rossant** [comment]
this is the intended behavior: you can easily see the global shortcuts, for view-specific shortcuts, the view needs to have the focus

maybe we could auto-generate a page in the docs with all shortcuts

**Comment by lepmik** [comment]
ok, but then you should change the following entry you get after ctrl+h to only h
show_shortcuts          : ctrl+h

**Comment by rossant** [comment]
agreed and done!
