### ISSUE TITLE
Traces crammed up on ubuntu

### ISSUE THREAD

**Issue by lepmik** [kwikteam/phy#338]
![image](https://cloud.githubusercontent.com/assets/3418096/8104396/b753dcb4-1030-11e5-91f8-bb81b12cbfec.png)

**Comment by rossant** [comment]
what is the problem exactly? this is the expected thing

**Comment by nippoo** [comment]
Aha - this is linked to #266 - we will soon implement dynamic high-pass filtering of the data so the LFP isn't shown (as a toggle-able option).

For the moment you can press Ctrl and [+] or Ctrl and [-] to decrease the channel height - this should do most of what you want!

**Comment by lepmik** [comment]
all right, just changed my graphics driver to NVIDIA and now ctrl [+] became enabled. Earlier I was not able to change the view.. Thanks
