### ISSUE TITLE
some kind of error on startup under pr345

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#346]
Looks like this:
![image](https://cloud.githubusercontent.com/assets/7590975/8194759/9c816ce6-1475-11e5-946a-4aa7410ede5c.png)

I did "conda install six" which seemed to work fine, and if I go into ipython, I can do "import six" without any error. So I'm not sure if it's really a problem with six or what.

**Comment by rossant** [comment]
oh this is not supposed to work. can you use `phy cluster-manual` instead?

**Comment by nsteinme** [comment]
Hm, well I worked out this strategy last time I tried to phy, because "phy
is not recognized as an internal or external command". Some kind of path
issue? I am in the phy/scripts directory though.

**Comment by nsteinme** [comment]
And I am in the venv that I've used phy from before.

**Comment by rossant** [comment]
do `python setup.py develop` in phy's root

**Comment by nsteinme** [comment]
Great, worked, thanks! Am I still using git for checking out different versions now, or has that been overwritten by this setup.py? I'm not exactly sure what it did exactly, I guess.

**Comment by rossant** [comment]
yeah it's still using git. I'm not sure how it could work before actually...
