### ISSUE TITLE
lines should persist for all ccgs

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#347]
I added lines with gui.views[4].view.lines = [-3, 0, 3] (great!) but when two clusters are selected, only the first panel shows the lines. They should all show them.

**Comment by rossant** [comment]
Fixed in last PR (yet to be pushed).

**Comment by rossant** [comment]
Oh and also, in the future PR, you'll be able to put default CCG lines in your user_settings.

**Comment by nsteinme** [comment]
Great!
