### ISSUE TITLE
Settable number of subplots in feature grid view

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#361]

**Comment by rossant** [comment]
@nsteinme would that be of any use? (i.e. having3 or 5 columns/rows instead of 4)
if we go ahead with your suggestions about the dimensions in the grid view, the number of subplots will be determined by the number of features per channel

**Comment by nsteinme** [comment]
Sure, although I doubt anyone would commonly want to go above 4x4 - it is already a lot! I'd say it's not a critical feature.

**Comment by nsteinme** [comment]
Well, thinking about it slightly differently, if you can choose any features including custom things, then the feature grid could easily become a "scatter plot matrix" - not for spike sorting but for later analyses - in which case you would for sure want to be able to select a custom number of subplots.
