### ISSUE TITLE
AssertionError in Waveforms view

### ISSUE THREAD

**Issue by danieljdenman** [kwikteam/phy#363]
this is only happening with some of my datasets, not all. not sure where the bug might be. 

runnning 'phy cluster-manual basename.kwik'. phy states normally and displays the first cluster:
![firstcluster](https://cloud.githubusercontent.com/assets/6707745/8219274/c4ed9f3c-14fd-11e5-9c86-5c5626058986.PNG)

when i attempt to advance to the second cluster , i get the following traceback:
![traceback](https://cloud.githubusercontent.com/assets/6707745/8219285/d6665eac-14fd-11e5-82a3-006c201eab94.PNG)

and the display updates to the following for the second cluster:
![secondcluster](https://cloud.githubusercontent.com/assets/6707745/8219323/0aa1f802-14fe-11e5-8a72-4fc5865f5637.PNG)

the feature plots all update, as do the stats and the correlograms. the same three unmasked channels are colored, even though the waveforms have updated. however, there is some lag between the the features, etc. changing and the waveforms updating without the mask. 
this traceback also happens if i pin the cluster to compare with the best match. 
like i said, only some datasets, not others.

**Comment by rossant** [comment]
could you send me your data (using dropbox gdrive or similar)? I'd need the kwik, kwx, kwd files.

**Comment by danieljdenman** [comment]
sure:
https://drive.google.com/folderview?id=0B0mC-hj9DiJMfk54TE1LU1BUWUVYcDBsOFBVR2hCb05jak9COWhwUW9iU3pjOF9hLXZ3MVE&usp=sharing
[it's looking like uploading will take ~40 minutes, from now.]

anecdotally, i tried with same data again yesterday, and the got the same
error immediately upon opening, first waveform. trying again this morning,
i got as far as merging two clusters before getting the same error.

i've now reported one issue through the google group and one through
opening a github issue. do you guys have a preference? i just want to do
what's easiest for your workflow.

**Comment by nippoo** [comment]
GitHub issue is much easier for us, thanks! :)

**Comment by danieljdenman** [comment]
i believe i've resolved this: deleting the basename.phy folder and regenerating the cluster store fixed it.   

if i [mistakenly] run phy for the first time on the .kwik before putting the results of kk2 [in the clu] back in to the .kwik, the cluster store is generated with just the one big cluster [from spikedetekt2]. seems like if i then put the clustering in, the cluster store doesn't match the clustering. maybe a way to check for this? anyway, integrating the detection and kk2 into phy will resolve the issue.

**Comment by rossant** [comment]
yes, it's a matter of days now...

**Comment by rossant** [comment]
I think the solution will be to *not* create the cluster store if there is just 1 cluster -- @nippoo wdyt?

**Comment by nippoo** [comment]
yes @rossant agreed - I thought we'd already decided this!

**Comment by rossant** [comment]
Closing this, tracking that feature in #369
