### ISSUE TITLE
mouse x coordinates in feature view off when away from origin of view

### ISSUE THREAD

**Issue by danieljdenman** [kwikteam/phy#367]
when drawing lassos, the translation of the mouse coordinates in the view into the feature space coordinates seems to depend on where in the view you click. the effect seems to depend on how far from the center of the view you are clicking.
to illustrate, i've tried to draw the same lasso around the same cluster while moving that cluster around the view.
centered in the view:
![at_origin](https://cloud.githubusercontent.com/assets/6707745/8237476/7d9dcf1a-15a4-11e5-8c4a-301ce1bce4b1.PNG)

up and to the left:
![upperleft](https://cloud.githubusercontent.com/assets/6707745/8237509/b574167e-15a4-11e5-8e25-6d3eff986332.PNG)

down and to the right:
![bottomright](https://cloud.githubusercontent.com/assets/6707745/8237517/bf7b2ad6-15a4-11e5-9d86-3ec1ec2c0f94.PNG)

**Comment by danieljdenman** [comment]
to clarify, the lasso translates fine if it already exists. i draw the lasso, take a screenshot, clear it, translate the feature space, and try to click the same points around the edge of the cluster, and the resulting lasso isn't quite where i clicked.

**Comment by rossant** [comment]
thanks -- i can reproduce it

**Comment by rossant** [comment]
a temporary work around might be to make the window as square as possible

**Comment by danieljdenman** [comment]
i'll try that. it's totally workable as it is, the user just has to try a few points and use his brain to compensate...
