### ISSUE TITLE
time in feature view problem

### ISSUE THREAD

**Issue by danieljdenman** [kwikteam/phy#368]
the feature vs. time plots looks weird in my data. screenshot below, and hopefully you see the same if you load the data i've sent you. from a single block recording, continuous, but all points are forced to two points, and a single point at a third timepoint. time in the traces view looks normal. 
![time](https://cloud.githubusercontent.com/assets/6707745/8237818/c38c3992-15a6-11e5-9f11-56fc041398fe.PNG)

[p.s. i really like this feature of phy. i actually asked about adding this to phy when speaking with kenneth, because i couldn't tell from my initial uses what those plots were supposed to be!]

**Comment by rossant** [comment]
can you remind me where does the data come from? openephys? not spikedetekt2/klustakwik?

**Comment by rossant** [comment]
i can't seem to be able to reproduce this:

![image](https://cloud.githubusercontent.com/assets/1942359/8238144/1d61627e-15f4-11e5-9619-9a08f3003264.png)

am i looking at the right thing?

**Comment by danieljdenman** [comment]
both - recorded with the openephys GUI into their .continuous, packed into a .dat with pack2 from here:
https://github.com/open-ephys/analysis-tools/blob/master/OpenEphys.py
and then put through spikedetekt2 and kk2.

**Comment by danieljdenman** [comment]
weird. exactly like that for all my data. maybe i'll just see if it persists through the next release.

**Comment by rossant** [comment]
oh, I'm running the latest PR, are you? (not sure it will change anything)

**Comment by danieljdenman** [comment]
i think so. 0.2.0.dev0 installed last week.

**Comment by rossant** [comment]
can you:

* run phy with `-i` (for IPython)
* `view = gui.get_views('features')[0]`
* `view.view.visual.spike_samples`

**Comment by danieljdenman** [comment]
In [2]: view.view.visual.spike_samples
Out[2]: array([    1035,     9625,    17780, ..., 12217766, 12224643, 12234842],
 dtype=uint64)

**Comment by rossant** [comment]
ok. python 2 or 3? Which version of Windows? 32-bit or 64-bit?

also, can you debug https://github.com/kwikteam/phy/blob/9896bc55373e9fe3e7bd0d9a69845a042716941d/phy/plot/features.py#L138 and look at the different variables? in particular look at t right before the function returns
it looks a bit like a int/float division issue...

**Comment by danieljdenman** [comment]
2.7, windows7 64bit, anaconda 64bit

you got it: float division issue. changed line 136 to:
m = float(t.max())

looks good:
![timefix](https://cloud.githubusercontent.com/assets/6707745/8240386/13ac2f62-15b7-11e5-93ee-e15888d7f2eb.PNG)

**Comment by danieljdenman** [comment]
sorry, line 148.

**Comment by rossant** [comment]
great! fixed in the latest PR
