### ISSUE TITLE
Proper format for logging, error, warn

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#38]
We need to standardise:

What format the error, warn, log should take (present tense, capitalisation, line breaks, when they should be used, etc)

Also a standard for breaking from functions after an error.

**Comment by rossant** [comment]
Have you found any document standardizing this, notably in the scientific Python world?
Also, might be worth looking at how IPython, scikit-learn, and NumPy do.

**Comment by rossant** [comment]
@nippoo can we close this?

**Comment by nippoo** [comment]
Oops. Yes, yes we can. I had a look through and it seems what we're doing is fairly standard.
