### ISSUE TITLE
snippets not working on windows under pr/397

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#412]
Console reports entering snippet mode when I type ":", but no commands seem to work, and now things like spacebar to change cluster don't work, even after pressing escape many times.

**Comment by rossant** [comment]
do you see the status bar? the colon? do you see what you type? is it just the escape which doesn't work? does the console reports quitting snippet mode?

**Comment by nsteinme** [comment]
Do not see the text appearing in the status bar. Console does not report
quitting snippet mode on escape.

**Comment by rossant** [comment]
i had the same problem on windows. then I started to debug by adding a `print("hey")` here: https://github.com/kwikteam/phy/blob/master/phy/gui/dock.py#L78
then  it worked, even after i removed the print statement...
can you try it too?

**Comment by nsteinme** [comment]
Hm, that didn't work for me. I also didn't see "hey" show up anywhere.

**Comment by rossant** [comment]
can you try `conda update --all`? which windows version do you have exactly?

**Comment by nsteinme** [comment]
Ok, I did that, nothing changed. Windows 7 Professional. What branch/pr of
phy should I be on right now? I am on 397.

**Comment by rossant** [comment]
#418

**Comment by nsteinme** [comment]
Ok. Still broken on that pr.

**Comment by rossant** [comment]
Options:

* make a minimal reproducible example and file an issue on Qt
* (simpler) just use another set of shortcuts, with a-z, space, and a few special characters. ugly but will definitely work fine on all platforms...

**Comment by nsteinme** [comment]
You're saying it's because of the colon? In that case, yeah, I vote we just
pick different shortcuts...

**Comment by rossant** [comment]
No sorry, it was just a note to myself... it will be exactly the same shortcuts for you, just the underlying implementation will be different. The colon is not the problem: detecting the keys pressed after it is. Basically Qt doesn't let you detect keystrokes globally -- you have to bind an action to `a`, one to `b`, one to `c`, etc. and manually append an `a`, etc to the snippet... So I'll do that for the 26 letters, 10 numbers, + a few others (space, dash, comma...)

**Comment by rossant** [comment]
OK, the PR now has a different implementation of the snippet system. I haven't tried on Windows, but chances are that it's going to work. Feel free to test @nsteinme  ...

**Comment by nsteinme** [comment]
Works! Genius. Are there more options than selecting clusters by number
yet? That alone is really great, though.

**Comment by rossant** [comment]
No, this is the only snippet I've implemented so far. You can add your own by adding the following to your user_settings:

```python

def change_correlogram_bins(gui, args):
    # `args` is a string with everything after the command and the space.
    # For example, typing `:cv w 100` results in `args = "w 100"`.
    # `what` is 'b' or 'w', `size` is a number
    # TODO: support setting both w and b at once.
    what, size = args.split(' ')
    size = float(size)  # in ms

    if what == 'w':
        half_width = size
        bin = None
    elif what == 'b':
        half_width = None
        bin = size
    else:
        raise ValueError("The command should be `w` or `b`.")

    for view in gui.get_views('correlograms'):
        view.change_bins(bin=bin, half_width=half_width)


cluster_manual_snippets = {
    'cv': change_correlogram_bins
}
```

I'd be happy to see what you come up with so that I can add them to the defaults!

**Comment by rossant** [comment]
(please `git pull` from the PR for this example to work..)
