### ISSUE TITLE
after merging two clusters, pressing <enter> should pin the newly created (and now selected) cluster

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#413]
After merging the new cluster is correctly displayed and seems to be selected. If you press enter here you'd expect to pin it and continue working on that cluster. 

Currently, instead, it pins the next one in "spacebar order", i.e. the next one you'd see if you pressed spacebar rather than enter.

**Comment by rossant** [comment]
Fixed on an upcoming PR (pushed once @nippoo merges the previous one)
