### ISSUE TITLE
cutoff in time view 

### ISSUE THREAD

**Issue by danieljdenman** [kwikteam/phy#421]
it seems only a subrange of time values are plotted in the feature views for some clusters. for example the cluster below, before and after splitting:
![time_cutoff](https://cloud.githubusercontent.com/assets/6707745/8366977/07b9f052-1b4f-11e5-95fc-8a3ea72cdb23.png)
before splitting, there are no points after a certain time, after splitting you can see that there were in fact spikes across the whole recording.

**Comment by rossant** [comment]
definitely weird! can I have a look at this dataset? (I'll also need to know what are these cluster numbers)

I'm wondering if it's some GPU bug...

**Comment by danieljdenman** [comment]
sure. i saw this before pr/397 as well, just fyi. 

actually - i see it in the other dataset that i put in my drive previously:
https://drive.google.com/open?id=0B0mC-hj9DiJMfk54TE1LU1BUWUVYcDBsOFBVR2hCb05jak9COWhwUW9iU3pjOF9hLXZ3MVE

here's an example from that set. cluster 144:
![timecutoff_u144](https://cloud.githubusercontent.com/assets/6707745/8367254/4fd3156a-1b51-11e5-9e9b-4fdd5d16355b.PNG)
and then after splitting [through a random part of the cluster]:
![timecutoff_u144_post](https://cloud.githubusercontent.com/assets/6707745/8367266/5f17dd26-1b51-11e5-807c-dad2bdeb3d00.PNG)

**Comment by danieljdenman** [comment]
[also, if you'd downloaded the data before, i updated the .kwik after my manual clustering so the numbering might be different than the one you downloaded before...]

**Comment by rossant** [comment]
thanks! I've found and fixed the bug in PR #418 (it was not GPU-related at all, just a stupid bug in the way spikes were subselected do match the maximum number of allowed spikes in the view)..
