### ISSUE TITLE
mean_probe_position incorrect

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#440]
Right now you are calculating the position of the cluster as:
mean ( masks * probe.positions )

But it should be:
sum ( masks * probe.positions ) / sum(masks)

[that's just the formula for center of mass]

Here's a specific line that computes it for each spike individually; you can probably use it directly if masks is the same size? I'm not sure.

masks = view.model.masks[...]
x = np.sum(masks*view.model.probe.positions[:,1],axis=1)/np.sum(masks,axis=1)

**Comment by rossant** [comment]
do you feel like trying to do a pull request and become an actual phy contributor? :) Max or I can show you how do to it

**Comment by nsteinme** [comment]
Ok! Will do it with max today.
