### ISSUE TITLE
Crash on win64 and h5py 2.5.0 (conda)

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#457]
This is caused by a bug in h5py with variable-length string attributes. The temporary solution is to downgrade to h5py 2.4.0

See https://github.com/h5py/h5py/issues/593

**Comment by nippoo** [comment]
Should we specify h5py 2.4.0 in the Windows install doc?

**Comment by rossant** [comment]
This is fixed now (works with 2.5.0)
