### ISSUE TITLE
Improve dev tools

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#462]
- [x] `pip install -r requirements-dev.txt` vs `pip install -r requirements-travis.txt`
- [x] remove dependency on `make` by adding custom distutils commands http://stackoverflow.com/questions/1710839/custom-distutils-commands/1712544#1712544

**Comment by rossant** [comment]
keep 0.2.0 milestone?

**Comment by nippoo** [comment]
The first point was fixed recently in https//github.com/kwikteam/phy/commit/09dfae4db06e7aa66e55e63e9881aa5721373d9e right? `pip install requirements-dev.txt` works for me now...

**Comment by rossant** [comment]
oh, right
