### ISSUE TITLE
Fix spike detection on multiple .dat files

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#482]
```
File "/apps/phy/phy/phy/utils/array.py", line 410, in get_excerpts
if len(data) < n_excerpts * excerpt_size:
TypeError: object of type 'ConcatenatedArrays' has no len()
```

**Comment by nsteinme** [comment]
Should this be reopened? It still isn't working for me on chandelier (maybe a version issue?). @nippoo let me know when I should try it.

**Comment by rossant** [comment]
Is phy up to date (`git pull`)? What error message? What does `phy -v` say?

**Comment by nsteinme** [comment]
Well unfortunately I'm not sure where phy is installed so I can't git pull
- is there a way to determine that? phy -v says:

0.2.0.dev0-git-v0.1.0-581-gc19a2b2b

**Comment by rossant** [comment]
ok i just updated it, can you try again?

**Comment by rossant** [comment]
for the record the path is `/apps/phy/phy`

**Comment by nsteinme** [comment]
Great, thanks - it's running, detecting spikes. Will let you know if/when
it finishes.
