### ISSUE TITLE
When selecting a cluster, WaveformView should centre on the cluster mean position

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#487]
When WaveformView is zoomed in (often the case on big IMEC probes), selecting a single cluster should jump so the cluster centre is centred in the view. If selecting two clusters, both cluster centres should be visible (jump to mean probe position)

**Comment by rossant** [comment]
better to implement this as part of the sparse array refactoring: then this behavior will be automatic!

**Comment by nippoo** [comment]
well, it still won't be automatic! because you'll still have the position of the channels... but yes :)

**Comment by rossant** [comment]
huh?

**Comment by rossant** [comment]
Done.
