### ISSUE TITLE
Save temporary clustering of KK2 in the Kwik file

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#501]
quoting @thesamovar 

```python
def f(kk):
  clusters = kk.clusters
  ... (do what you want with the clusters)

kk = KK(...)
kk.register_callback(f)
```

This f gets called at the end of each iteration.

If you want every N iterations, inside f put:

```python
if kk.iteration%N==0
```

**Comment by rossant** [comment]
@thesamovar  it seems like the callback is called many times during a split iteration? does that make sense? it looks like it's stuck in an infinite loop and the split never ends...

**Comment by thesamovar** [comment]
Ah yes, my mistake I should have mentioned that. During splitting, a subset/copy KK object is created, and this inherits the callbacks. To ignore that, add the following at the beginning of the callback function:

```
if kk.name!='':
    return
```

**Comment by thesamovar** [comment]
It's not stuck in an infinite loop though, it's just very slow to do the splitting.
