### ISSUE TITLE
model.features should be a 3D array

### ISSUE THREAD

**Issue by shabnamkadir** [kwikteam/phy#515]
```
model = KwikModel(kwik_path)

masky = model.masks[:] # Has shape (number of spikes, number of channels)
fetty = model.features[:]  # Has shape (number of spikes, number of features)

```

Typically number_of_channels != number of features. This is annoying for developers of, e.g. KlustaKwik.

**Comment by rossant** [comment]
yeah I agree, I thought an issue was already open but I can't find it!

**Comment by rossant** [comment]
actually if you want per-cluster features, you should use the cluster store (much more efficient), and that one will have the correct shape, ie `(n_spikes, n_channels, n_features)`

**Comment by shabnamkadir** [comment]
At the moment I just want to convert back to the legacy format: fet and fmask files.
