### ISSUE TITLE
Can SpikeDetekt2 run multiple threads?

### ISSUE THREAD

**Issue by ereming** [kwikteam/phy#534]
I know that klustakwik2 uses multithreading (I tested a dataset a month ago which finished in ~5 hours with kk2 vs > 7 days with kk1), does this feature also exist in SpikeDetekt2? I'm running the phy pipeline right now and top is showing that only one core is being used.

**Comment by rossant** [comment]
Not at the moment, but this is planned for the next 0.3 version (see #420)

**Comment by ereming** [comment]
I see, thanks!
