### ISSUE TITLE
Manual clustering GUI won't open in Session

### ISSUE THREAD

**Issue by ereming** [kwikteam/phy#544]
I can run the GUI straight from the command line, but not within a session. I think it's QT related, because when I run

$ phy.enable_qt()

the results is:

[W] Qt event loop not activated.

Running on OSX.

Thanks!

**Comment by rossant** [comment]
What command do you run exactly? Are you in IPython?

**Comment by ereming** [comment]
The exact commands I'm using are

$ source activate phy
$ python
$ import phy
$ phy_enable_qt()

**Comment by rossant** [comment]
OK; this may be fixed in the future. In the meantime, can you use `ipython` instead of `python`?

**Comment by ereming** [comment]
Yep, that works. Thanks!

**Comment by rossant** [comment]
closing in favor of #560
