### ISSUE TITLE
sampling an interval doesn't work if you don't start at zero

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#565]
Line 97 of detect/spikedetekt.py is a bug: it checks that start is less than n_samples, but if an interval is used, n_samples is the number of samples within the interval whereas start is in absolute samples within the whole file. E.g. if you ask for the interval 9,12 with sample_rate=20000, then start will be 180000 but nsamples will only be 60000, so the assertion will fail though the data and numbers are fine. 

Also can we clear the NotImplementedError, line 100? I would like to use this function and I don't much care whether the spike times are referenced to the start of the interval or to the start of the total file (in fact maybe the former is preferable?).

**Comment by rossant** [comment]
good catch, it should be `assert 0 <= start < end`, PR welcome :)

**Comment by rossant** [comment]
> Also can we clear the NotImplementedError, line 100? I would like to use this function and I don't much care whether the spike times are referenced to the start of the interval or to the start of the total file (in fact maybe the former is preferable?).

I'm not sure. @nippoo ?

**Comment by nsteinme** [comment]
Yes, but so far posting an issue here is easier for me ;) I need to take
some time and get good at github...

**Comment by rossant** [comment]
it's always good to post an issue before proposing any PR...
@nippoo we're counting on you to make @nsteinme a git expert

**Comment by nsteinme** [comment]
Don't worry he's doing his best, I'm just being a slow learner ;)

**Comment by nsteinme** [comment]
I will make a different issue about the NotImplementedError, since it needs to stay until that is implemented...
