### ISSUE TITLE
Number of clusters per view

### ISSUE THREAD

**Issue by shabnamkadir** [kwikteam/phy#594]
Phy only allows the user to view 13 channels at once, but the error message says 14. This discrepancy needs correcting.

In [30]:

gui.select([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

21:28:46 [W] You cannot select more than 14 clusters in the GUI.

**Comment by rossant** [comment]
feel free to propose a PR
