### ISSUE TITLE
Improve ClusterView

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#60]
* Show selected/unselected
* Allow multiple selection
* Require to find the appropriate HTML controls

**Comment by nippoo** [comment]
Info needed per cluster:

- number [id]
- quality
- number of unmasked channels
- estimated (x, y, r)
- number of spikes
- list of tags
- current colour

- ACG
- mean waveform[s]
- firing rate histogram

- currently selected cluster CCG, similarity score
