### ISSUE TITLE
Auto-line-wrap and indent log entries

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#615]
If they go over 79 characters total, we should line wrap them in a sensible way and indent successive wraps to prevent auto-wrapping which is much less readable.

**Comment by rossant** [comment]
I'm not sure it is good practice... The standard is 1 message = 1 line. I'd rather have shorter logging messages, and read log files with autowrap turned off

**Comment by rossant** [comment]
taking care of in the refactoring
