### ISSUE TITLE
model.close() is not called on exit

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#618]
If the GUI is closed with alt+f4 or the close button, the file handles aren't properly closed.

**Comment by nippoo** [comment]
... or maybe they are. Trying to call `self.close()` from `self.__del__` results in nasty warnings like `C:\Users\Max\miniconda3\lib\site-packages\h5py\_hl\files.py:290: RuntimeWarning: Found murdered identifier 112489032 of kind <class 'NoneType'> HDF5 id 1376727968`...

**Comment by rossant** [comment]
murdered? omg

**Comment by nippoo** [comment]
yeah. thought this would be a simple bug. I'm actually not sure it matters. I think all the files will individually be closed on exit... so it might not be a problem

**Comment by rossant** [comment]
there are segfaults when quitting sometimes, so something might be wrong...
