### ISSUE TITLE
kk2 log missing

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#623]
In the ".log" file, all you get is "running klustakwik". It should at least report the initial parameters and files used, also each time an iteration is completed - how many clusters, nChanged, and timestamps.

**Comment by rossant** [comment]
@thesamovar how is KK2 handling log files?

**Comment by thesamovar** [comment]
If it's run from phy I don't handle it at all (kk2 doesn't do any file handling when run from phy).
