### ISSUE TITLE
Backport file format fixes in KV? 

### ISSUE THREAD

**Issue by rossant** [kwikteam/phy#628]
to make phy-created files compatible with KV? might be simpler for users if things "just worked" rather than having x slightly incompatible versions of the files

**Comment by nippoo** [comment]
I guess we should make the waveforms dynamically loaded too, then? happy to do this but it should probably be a KV issue...

**Comment by rossant** [comment]
Ahhh you're right for the waveforms. Then it's not that simple, because then you need the raw data, but it's using kwd and not .dat etc etc. Not sure if it's worth it then.

I guess the question is why people want to use KV? Maybe they lack the cluster view?

**Comment by nippoo** [comment]
Well the ClusterView, but probably also the SimilarityMatrixView for smaller datasets... perhaps compatibility with .clu files? Or one of a few blocking bugs (kk2 parameters not working... etc)!

**Comment by nippoo** [comment]
Closing in favour of https://github.com/klusta-team/klustaviewa/issues/58
