### ISSUE TITLE
ctrl+h does not show shortcuts for individual views

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#629]
No matter which window I have selected, pressing `ctrl+h` returns only `Keyboard shortcuts for ClusterManualGUI`. So I cannot find a way, for example, to see the shortcut keys for scaling the waveform view.

**Comment by rossant** [comment]
press `h` instead to see the shortcuts for a given window

**Comment by nsteinme** [comment]
Aha, well, it must be said - that would be a useful thing to have correct
in the documentation ;)

I have proposed a PR to the documentation fixing this and adding some other
things.
