### ISSUE TITLE
sample parameters file not downloading

### ISSUE THREAD

**Issue by nkalipi** [kwikteam/phy#638]
In the sample given for automatic clustering in the phy website, there is a commandd to download the hybrid_10sec.prm file.
phy download hybrid_10sec.prm.

when i execute this command in the powershell of windows, i get an error as follows:
HTTPError: 404 Client Error: Not Found

I am using windows 10 and powershell in windows, python 3.4, phy 0.2.1

![error](https://cloud.githubusercontent.com/assets/14220858/9793705/db884f40-57b4-11e5-8e4c-71777fbcc16b.JPG)

**Comment by rossant** [comment]
it seems that you have an extra dot at the end of the file: try removing it

**Comment by nippoo** [comment]
Looking at the logs, someone has recently requested ```hyrbid_10sec.prm``` which is a typo. Can you check you've got the correct full filename?

**Comment by nkalipi** [comment]
i ran the command as given in the website, this is what i am getting:

it says that the file cannot be found at the website specified..
![error 1](https://cloud.githubusercontent.com/assets/14220858/9794079/245bb48a-57b7-11e5-9704-3482c6d40b79.JPG)

**Comment by nippoo** [comment]
Can you try browse to that URL in your web browser? Have you got some sort of institutional proxy or firewall?

http://phy.cortexlab.net/data/samples/

**Comment by nkalipi** [comment]
yep that worked! thanks!! somehow my terminal is not able to point to that website..
Thanks @nippoo
