### ISSUE TITLE
waveform display offset

### ISSUE THREAD

**Issue by danieljdenman** [kwikteam/phy#639]
i'm seeing an issue with the offset of the extracted waveforms displayed in the Waveform view - they appear to be offset in the amplitude dimension:

![waveformdisplay_offset](https://cloud.githubusercontent.com/assets/6707745/9803155/b5f7c63c-57d4-11e5-86f2-752c057cd87c.png)

this data was sorted using phy2.1, displayed with 2.2. running on mac with anaconda.

**Comment by danieljdenman** [comment]
amended: true for some data sets, not others. working on determining the unifying factor between datasets with this issue.

**Comment by nippoo** [comment]
any updates @danieljdenman? maybe the .prb might be different / wrong / there might be a huge DC offset or something.

I'm working on the WaveformView this week so if you haven't figured it out, I'd love to have a copy of a dataset which exhibits this behaviour so I can troubleshoot myself!

**Comment by danieljdenman** [comment]
i never quite figured out what was the cause. deleting the store [that was created with 2.1] and remaking it with 2.2 solves the issue for me. since everything is updated now, i haven't seen any issues.

**Comment by nippoo** [comment]
alright, closing for now!
