### ISSUE TITLE
stalled installation win7

### ISSUE THREAD

**Issue by amansaleem** [kwikteam/phy#655]
I am trying to install phy on Window 7, using the instructions provided. I installed POwerShell and I have the version (up to date) of C++ already installed.

The installation in the PowerShell window stops right after I start (image) 
![image](https://cloud.githubusercontent.com/assets/14873029/10137427/66200b58-65f1-11e5-8e0c-1c025b1d8a4b.png)

**Comment by nippoo** [comment]
How long does it stop for?

**Comment by amansaleem** [comment]
I checked after 3 hours and nothing happened, so I closed the session. If
you are coming down to old street for electrophysiology club, you can have
a go yourself.

On Tuesday, 29 September 2015, Max Hunter <notifications@github.com> wrote:

> How long does it stop for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kwikteam/phy/issues/655#issuecomment-144132618>.
>


-- 
Sent from Mobile

**Comment by nippoo** [comment]
Pressing Ctrl+C solved this issue. Still not sure what/why happened...
