### ISSUE TITLE
spikedetekt is way too slow

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#671]
I even have a constructed/simulated file with literally only about 77k spikes in it, and it's taking hours to find them all. It makes no sense! There is probably some kind of really simple optimizations that can be done to make it speed up by a zillion. Whatever it is doing currently is the wrong algorithm, and it's frustrating.

**Comment by rossant** [comment]
> There is probably some kind of really simple optimizations that can be done to make it speed up by a zillion

Cool, it won't take you long to do a PR then?

**Comment by nsteinme** [comment]
I don't know what they are! :) I just wanted to post this issue so it is
"on the list".

**Comment by rossant** [comment]
Something that comes to my mind is waveform interpolation: this is one of the bottlenecks, and it looks like [it is done on all channels currently](https://github.com/kwikteam/phy/blob/master/phy/traces/waveform.py#L150), whereas it should probably be done on the unmasked channels only, especially with huge probes likes yours...

**Comment by rossant** [comment]
closing since spikedetekt has been moved into [klusta](https://github.com/kwikteam/klusta), feel free to reopen there if necessary
