### ISSUE TITLE
Waveforms not loading for cluster-manual

### ISSUE THREAD

**Issue by swbeckwi** [kwikteam/phy#680]
I've already run spikesorting on several data sets. I've already manually clustered them with cluster-manual afterwards for several of them. Now when I start cluster-manual the waveforms are loading. First the waveforms wouldn't load in the probes geometry. Now I can't see them at all. I can still see and operate the traces, features, correlograms etc., but not waveforms.

**Comment by rossant** [comment]
do you have the same problem with the latest version? (the new command is `phy kwik-gui file.kwik`)
