### ISSUE TITLE
Lasso tool missing

### ISSUE THREAD

**Issue by ananmoran** [kwikteam/phy#694]
Hi,
It might that I've failed to locate it, but it seems that the lasso tool in the gui was removed in the new version of phy-gui. Any intentions to put it back in again? I found the ability to correct the automatic clustering essential.

Thanks
Anan

**Comment by rossant** [comment]
Try ctrl + click on the polygon points

**Comment by ananmoran** [comment]
Works. Thanks. I did not find the documentation for that functionality. 
Another desired functionality of the polygon might be to remove undesired spikes from a selected cluster (for example by pressing ctrl+shift). would you consider adding that functionality? (or is it already implemented?)

**Comment by rossant** [comment]
Yes I need to add this to the doc!
If you select some spikes and split with `k`, you get two new clusters, one with the selected spikes, another with the rest of the spikes. Then you can move the undesired cluster to the "noise" group. Does that answer your question or didn't I understand correctly?

**Comment by ananmoran** [comment]
Exactly! That's perfect. 
Much obliged

**Comment by rossant** [comment]
you're welcome!
