### ISSUE TITLE
how to remove a view from gui

### ISSUE THREAD

**Issue by chongxi** [kwikteam/phy#697]
From the document, I understand to add a vispy view by `gui.add_view(canvas)`
But how to remove some canvas from the gui?
Can't find this in the doc.

**Comment by chongxi** [comment]
No solution? once a View() is created in the GUI, there is no interface to close it?

**Comment by rossant** [comment]
have you tried `view.close()`?

**Comment by chongxi** [comment]
If you use view.close(), the content of the view will close indeed. But the Qt instance is still in the GUI.
