### ISSUE TITLE
'Move' menu function broken

### ISSUE THREAD

**Issue by crnolan** [kwikteam/phy#703]
More generally, menu items calling functions with no default parameters, but with non-supplied parameters (via partial) fail with errors of the form:

`22:56:01 [E] cli:37               An error has occurred (TypeError): move() missing 2 required positional arguments: 'cluster_ids' and 'group'`

**Comment by crnolan** [comment]
I've added a fix for this at https://github.com/crnolan/phy/commit/b6db0851f53c0e7477b2f2839843e53189e6c76a. If anyone can verify this fix, I'll generate a pull request.

**Comment by rossant** [comment]
thanks, yes, please do submit a PR!
