### ISSUE TITLE
Make TraceView use vertical spatial channel order

### ISSUE THREAD

**Issue by mspacek** [kwikteam/phy#717]
Unless I'm doing something wrong with my custom `.prb` file, it seems that the TraceView channels are sorted in numerical order. It would be much better to sort them in vertical spatial order, so that spikes show up as spatially localized events. Depending on the channel mapping, the waveforms of a multichannel spike can end up scattered across the probe. Vertical spatial order would also make the TraceView more directly comparable to the WaveformView.

**Comment by rossant** [comment]
I think it could be a good idea. @nsteinme @yger ?

**Comment by nsteinme** [comment]
I definitely think it's best to sort them in vertical spatial order - as @mspacek says, that makes it comparable to the waveform view, and matches your logical conception of the relationship between channels. I thought that's how it already was! Mine come out that way - but for my recent recordings, the two are identical so I guess I just didn't notice it was doing something different.

**Comment by yger** [comment]
Indeed, I also think this has to be the case. It would be easier to read for vertical probes layout. For square MEA/probes, this will still be annoying, but I do not think there is much you can do about that.

**Comment by mspacek** [comment]
Thanks Cyrille, but from what I can tell, the TraceView is not in vertical spatial order. Here's a screenshot:

![screenshot - 16-10-27 - 04 17 22 pm](https://cloud.githubusercontent.com/assets/799467/19770849/19cc6b46-9c61-11e6-97c4-ce862388ec1f.png)

The channel labels in the TraceView don't match vertically with those in the WaveformView. Also, each spike in the TraceView is scattered across the probe, instead of being spatially localized. Here are my crresponding .prm and .prb files:


[prm_prb_files.zip](https://github.com/kwikteam/phy/files/556113/prm_prb_files.zip)

**Comment by rossant** [comment]
could you send me the full dataset?

**Comment by mspacek** [comment]
Sure. Here's a 10 sec excerpt of data from a single column A1x32 NeuroNexus probe. All the relevant files should be there. Let me know once you've downloaded it, so I can delete it from this file sharing site:

https://mega.nz/#!tRtD1LTS!mG6cGNiKv-m-P9yAK4o6frNgUDJWFKWWuB6WMlYkdik

**Comment by rossant** [comment]
Thanks. Downloaded, I'll have a look.

**Comment by rossant** [comment]
OK I pushed a fix on master, can you try again?

**Comment by micheleacox** [comment]
For clarification, to pull fixes from the master, do we use: 

pip install phy phycontrib --upgrade

**Comment by rossant** [comment]
No, this will upgrade to the latest release. Use the following command to upgrade to the development version on master:

```
pip install git+https://github.com/kwikteam/phy.git git+https://github.com/kwikteam/phycontrib.git --upgrade
```

**Comment by mspacek** [comment]
Yup, that did it. Thanks! Ha, having to argsort an argsort sounds familiar.
