### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by llobetv** [kwikteam/phy#736]
Hello,

I'll list some issue that i encounter with  circus-gui-pyton (Normally i use development version) :

- Trace view take only depth to organize channel so it become unreadable
![image](https://cloud.githubusercontent.com/assets/22896067/21682699/4c34fbda-d356-11e6-9680-a88a24608cf6.png)
- When i used kwik gui there was a tool that illuminated spike of 1 cluster on raw trace and i dont manage to use it with circus, it was very usefull to explore quality of 1 cluster
- Something probably specific to spyking-circus : The colorization of the trace is too large and too extensive make it harder to read (sometimes 2-3 color overlap, and in this case which one "win"?), It should be fix whithin exportation step? (reduce interval and Coloring only channel where thereshold is Exceeded like when template dictionary is build)

Best,
Victor

**Comment by rossant** [comment]
In the development version, you have the alt+s shortcut to toggle the color of the spikes in the trace view. It alternates between highlighting the spikes of the selected clusters, or all spikes.
