### ISSUE TITLE
segfault when importing phy.cluster and phy.gui after installing pyqt5 from pip

### ISSUE THREAD

**Issue by lepmik** [kwikteam/phy#740]

**Comment by rossant** [comment]
phy doesn't work with PyQt5 unfortunately https://github.com/kwikteam/phy/pull/735

**Comment by lepmik** [comment]
ok, I can live with that

**Comment by rossant** [comment]
closing in favor of #664

**Comment by rossant** [comment]
if someone finds a workaround for https://github.com/ContinuumIO/anaconda-issues/issues/1267 I'd be happy to see it!

**Comment by dragly** [comment]
We had the same issue in other projects and I found the following combination to work with Python 3.5:
```
pip install pyqt5==5.7 sip==4.18
```
But I guess this workaround is very temporary and will break with newer versions of Python.
