### ISSUE TITLE
'ClusterView' does not have 'groups' field in windows

### ISSUE THREAD

**Issue by zhuangjun1981** [kwikteam/phy#745]
Hi,

I have noticed that the 'ClusterView' in my phy interface does not have 'groups' field, but it shows up in my colleague's computer. I guess this maybe due to the operating system (I am using windows, he's using mac). Could anyone add this feature to window's version since it is really useful?

Thanks a lot

Jun

**Comment by rossant** [comment]
I think you'll get this feature if you install the latest development version as explained here: https://github.com/kwikteam/phy#installing-the-development-version

**Comment by zhuangjun1981** [comment]
That works. Thanks
