### ISSUE TITLE
Shortcuts in ClusterView not working

### ISSUE THREAD

**Issue by nikolaskaralis** [kwikteam/phy#749]
The shortcuts of the Clustering menu (including Undo etc) are not working when the selected cluster is in ClusterView.
They work when you select a cluster in the SimilarityView, but usually one makes the clustering decisions by selecting the cluster in the ClusterView.

**Comment by rossant** [comment]
I don't seem to be able to reproduce this. Could you specify the exact situation and commands that led you to this bug?

**Comment by nikolaskaralis** [comment]
I think this might have been a confusion on my side. It seems you need to use Move All commands, not the move best or move similar.
I tried it again with the Move All and it works.
