### ISSUE TITLE
buggy .phy folder when changing channel group

### ISSUE THREAD

**Issue by lepmik** [kwikteam/phy#752]
When changing channel-group it seems that phy tries to load memcahe from previous channel-group from the .phy folder. In some cases it seems to give erroneous waveforms.

**Comment by rossant** [comment]
Is this fixed in the development version?

**Comment by lepmik** [comment]
I actually delete the .phy folder every time I open the gui, sorry, haven't had time to look more closely into it.

**Comment by rossant** [comment]
If you install the development version of phycontrib the bug should be fixed. Feel free to reopen if it is not!

**Comment by lepmik** [comment]
aha, saw your commit now, guess I should merge upstream a bit more often. Thanks
