### ISSUE TITLE
[fixed] template-gui fills memory and also crashes when loading data

### ISSUE THREAD

**Issue by Kelarion** [kwikteam/phy#777]
I'm using phy on Neuropixels data that was processed with kilosort, but when I run template-gui my 64GB of ram gets filled up rapidly, leading to a computer crash if I don't abort phy:

![memoryfull](https://user-images.githubusercontent.com/20094477/33570538-10a6add6-d925-11e7-8721-c6233a32e157.PNG)

It happens during:
```
15:48:04 [D] gui:428    Load the GUI state from `C:\Users\Matteo A\.phy\TemplateGUI\state.json`.
15:48:16 [D] utils:51   Get box size for 374 points.
```

The strange part is that phy has worked fine on this machine before, and I'm not sure what change I made to break phy. All I can think is that I installed some packages outside the phy environment. 

It seems that phy might be loading the entire *.bin file into memory, which seems strange. When I run Phy on a much smaller dataset, it is fine with memory and manages to open the phy window, but then crashes when loading the data. `phy --debug` doesn't return any issues either.

I'm using the latest Anaconda, with python 3.6.3. Maybe this is an issue with my python? But the problem persisted after I reinstalled Anaconda and tried out-of-the-box Miniconda. 

Any idea what this might be? Many thanks in advance.

NB I'm running from the appropriate directory, and I get the same problems after reinstalling the latest version of phy and phycontrib (`pip install phy phycontrib --upgrade`). This also happens with both the vanilla phy and development version.

**Comment by Kelarion** [comment]
This is what I mean by 'crashes when loading data':
![phycrash2](https://user-images.githubusercontent.com/20094477/33605349-45d017ea-d9b1-11e7-8425-87d65ba6d57e.PNG)

**Comment by Kelarion** [comment]
I fixed it by deleting the */.phy folder first created created by:
`[D] config:87            Creating default phy config file at 'C:\Users\Matteo A\.phy\phy_config.py'.`
and then creating a new one (by running template-gui). 

It seems like it was an issue with */.phy/TemplateGui/state.json, since the old and new phy_config files are identical. Beyond that, I can't say.

**Comment by rossant** [comment]
Good to know! It might have been the trace view config which specified a huge loading interval... We should probably put an upper limit on the window time interval of the trace view.
