### ISSUE TITLE
Waveform channel mapping

### ISSUE THREAD

**Issue by johnleeuk12** [kwikteam/phy#809]
Hi,

Thank you for developping Phy!
I'm currently using template-gui with kilosort, and cannot seem to get more than one column of channel waveforms with Template-gui. I'm using the eMouse code from Kilosort, and it seems to be displaying channels with a unique y coordinate (regardless of x). Overlapping y coordinates are not shown in the gui, and x coordinates does not seem to have an effect. I've verified this with the .npy Channel position and Channel map files.  Has anyone else had a similar issue?

**Comment by johnleeuk12** [comment]
I would like to also add that I'm using phy 1.0.9, and when I look at Probeview, both columns are there, but Waveform view only shows me one. This is a screenshot of the test dataset from
 https://phy-contrib.readthedocs.io/en/latest/template-gui/#test-datasets

![image](https://user-images.githubusercontent.com/35505724/49612438-bdc21000-f972-11e8-95d4-0f526e299ecc.png)

**Comment by rossant** [comment]
maybe try to delete `~/.phy/` to reset the view state of the waveform view?

**Comment by johnleeuk12** [comment]
Yep. That worked. Thank you!
