### ISSUE TITLE
Problem with setting bin and window

### ISSUE THREAD

**Issue by alejoe91** [kwikteam/phy#813]
Hi guys,

Probably (and hopefully) this is a quick one!

Using the dev version of phy and the template-gui phy-contrib (with pyqt5), when I try to set bin or set window fr the crosscorrelogram I get (using the `--debug` option):
`[W] actions:171          Invalid function arguments: expecting 1 but got 0`

Has anyone experienced the same issue? 

Thanks,
Alessio

**Comment by rossant** [comment]
Thanks for the bug report, this should be fixed on the dev branch!

**Comment by alejoe91** [comment]
Thanks! :)
