### ISSUE TITLE
WaveformView does not show spike waveforms

### ISSUE THREAD

**Issue by wehrlab** [kwikteam/phy#814]
Hi,
I am using Kilosort to cluster tetrode data that's collected in Open Ephys. I have installed and used phy before and had not experienced this issue. It looks like the waveform view is showing flat lines, instead of spike waveform. It does not appear to be a scaling issue, since changing the scale does not fix it. I'm wondering if there is a variable that needs to be adjusted in my configuration file during clustering or if there are some libraries that I'm missing. Thanks. 
![phy_issue](https://user-images.githubusercontent.com/6556623/52386552-6eb05e00-2a3b-11e9-88ad-800a03911d72.PNG)

**Comment by rossant** [comment]
Could you try to rename, in your home directory, your `~/.phy` to `~/.phy~` (there might be abnormal scaling parameters in the autogenerated config files)? Same for the `.phy` subfolder in your data repository.

**Comment by adehad** [comment]
@wehrlab I had a similar abnormal scaling issue after moving to the `gloo` branch. I used the `Ctrl+Up` shortcut until I could see my waveforms.
