### ISSUE TITLE
Phy still looks like old version

### ISSUE THREAD

**Issue by LibiF** [kwikteam/phy#820]
I downloaded and installed the new phy version, but it still looks like the old version:
1. No column with the suggested classification ( good, mua,...)
2. No amplitude histogram.
3. No probe view
4. Traceview doesn't work properly
When I activate phy it says "Package klusta not installed: the KwikGUI will not work."
Where can I find klusta? Can it be the reason for the old "view"?
Thanks
![phyview](https://user-images.githubusercontent.com/38905822/57312884-169afd80-70f7-11e9-8877-297f9b069f00.JPG)

**Comment by rossant** [comment]
There is no column with the cluster classification (this is only shown in the color of the rows in the cluster view). The amplitude view is working but you have very few spikes in the screenshot. For the trace view you just need to reduce the scaling.
